version: '3.8'
services:
  backend:
    build:
      context: ./Autodrive-1
      dockerfile: Dockerfile
    container_name: autodrive-backend
    ports:
      - "8080:8080"
    environment:
      # Use a non-SRV MongoDB URI to avoid DNS SRV lookups inside the container
      # Adjust this to your actual MongoDB host if not running locally
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/autodrivedb?retryWrites=true&w=majority
      JWT_SECRET: 0920345690887756372139595932029349932010300000000000000983375743220000000
    networks:
      - autodrive-network

  frontend:
    build:
      context: ./autofront-send-a
      dockerfile: Dockerfile
    container_name: autodrive-frontend
    ports:
      - "3000:80" # Mappe le port 3000 de votre machine hôte au port 80 (port de Nginx) du conteneur fronten
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/autodrivedb?retryWrites=true&w=majority
      JWT_SECRET: 0920345690887756372139595932029349932010300000000000000983375743220000000
      API_BASE_URL: http://backend:8080/api
      AI_API_URL: http://chatbox:8000
      WEBSOCKET_URL: http://backend:8080/ws
    depends_on:
      - backend
      - chatbox
    networks:
      - autodrive-network
  chatbox:
    build:
      context: ./chatbox
      dockerfile: Dockerfile
    container_name: chatbox
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: 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
    networks:
      - autodrive-network
    depends_on:
      - backend


networks:
    autodrive-network:
        driver: bridge